DROP TABLE IF EXISTS tarefa;
DROP TABLE IF EXISTS `user`;

CREATE TABLE IF NOT EXISTS `user` (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(80) NOT NULL,
    email VARCHAR(90) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS tarefa (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(90) NOT NULL UNIQUE,
    description VARCHAR(400) NOT NULL,
    scheduled TIMESTAMP NOT NULL,
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES `user`(id)
);
