CREATE TABLE  usuario (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE tarefa (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL,
    scheduled TEXT NOT NULL,
    user_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES usuario(id) ON DELETE CASCADE
);
